# Generated by Django 5.2 on 2025-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='not_available',
            field=models.CharField(default='not available', max_length=20),
            preserve_default=False,
        ),
    ]
