# Generated by Django 5.2 on 2025-06-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0004_show_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='not_available',
        ),
    ]
