# Generated by Django 5.2 on 2025-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0007_otpstorage_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstorage',
            name='counter',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
