# Generated by Django 5.2 on 2025-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0008_otpstorage_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstorage',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
