# Generated by Django 5.2 on 2025-06-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0009_alter_otpstorage_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpstorage',
            options={'get_latest_by': 'created_at'},
        ),
    ]
