# Generated by Django 5.2 on 2025-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0010_alter_otpstorage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpstorage',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
