# Generated by Django 5.2 on 2025-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0011_alter_otpstorage_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstorage',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
