# Generated by Django 5.2 on 2025-06-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0012_otpstorage_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpstorage',
            name='is_expired',
        ),
    ]
