# Generated by Django 5.2 on 2025-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0013_remove_otpstorage_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstorage',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
