# Generated by Django 5.2 on 2026-02-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0018_turf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbooking',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
