# Generated by Django 5.2 on 2026-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0019_turfbooking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='seat',
            name='tier',
            field=models.CharField(default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='show',
            name='format',
            field=models.CharField(default='2D', max_length=20),
        ),
    ]
